/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ps.gui;

import javax.swing.JDesktopPane;


/**
 *
 * @author Admin
 */
public class Dashboard extends javax.swing.JFrame {
    

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoSite = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titleBar = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        userName11 = new javax.swing.JLabel();
        userName8 = new javax.swing.JLabel();
        userName5 = new javax.swing.JLabel();
        others = new javax.swing.JLabel();
        activity = new javax.swing.JLabel();
        editProfile = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        criminalInfo = new javax.swing.JLabel();
        userName6 = new javax.swing.JLabel();
        generalDiary = new javax.swing.JLabel();
        others2 = new javax.swing.JLabel();
        userName10 = new javax.swing.JLabel();
        profileImg1 = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        policeInfo = new javax.swing.JLabel();
        userName3 = new javax.swing.JLabel();
        others1 = new javax.swing.JLabel();
        dumInfo = new javax.swing.JLabel();
        userName7 = new javax.swing.JLabel();
        personalInfo = new javax.swing.JLabel();
        userName9 = new javax.swing.JLabel();
        addNewAdmin = new javax.swing.JLabel();
        caseInfo = new javax.swing.JLabel();
        userName1 = new javax.swing.JLabel();
        dash1 = new javax.swing.JLabel();
        menuItem = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoSite.setBackground(new java.awt.Color(0, 51, 51));
        logoSite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Police Dashboard");
        logoSite.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 30));

        getContentPane().add(logoSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 60));

        titleBar.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 0, 1050, 60));

        menuBar.setBackground(new java.awt.Color(51, 51, 51));
        menuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userName11.setForeground(new java.awt.Color(255, 255, 255));
        userName11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sports-gun-24.png"))); // NOI18N
        menuBar.add(userName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 50));

        userName8.setForeground(new java.awt.Color(255, 255, 255));
        userName8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Plaster.png"))); // NOI18N
        menuBar.add(userName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 50));

        userName5.setForeground(new java.awt.Color(255, 255, 255));
        userName5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vampire.png"))); // NOI18N
        menuBar.add(userName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 50));

        others.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        others.setForeground(new java.awt.Color(255, 255, 255));
        others.setText("Others");
        menuBar.add(others, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 160, 50));

        activity.setForeground(new java.awt.Color(51, 255, 0));
        activity.setText("Online");
        menuBar.add(activity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        editProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editProfile.setForeground(new java.awt.Color(255, 255, 255));
        editProfile.setText("Edit Your Profile");
        menuBar.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 110, -1));

        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboard_1.png"))); // NOI18N
        menuBar.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 50));

        criminalInfo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        criminalInfo.setForeground(new java.awt.Color(255, 255, 255));
        criminalInfo.setText("Criminal Information");
        criminalInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criminalInfoMouseClicked(evt);
            }
        });
        menuBar.add(criminalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, 50));

        userName6.setForeground(new java.awt.Color(255, 255, 255));
        userName6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Account card.png"))); // NOI18N
        menuBar.add(userName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 50));

        generalDiary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generalDiary.setForeground(new java.awt.Color(255, 255, 255));
        generalDiary.setText("General Diary");
        generalDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generalDiaryMouseClicked(evt);
            }
        });
        menuBar.add(generalDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 160, 50));

        others2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        others2.setForeground(new java.awt.Color(255, 255, 255));
        others2.setText("Arms & Ammos");
        others2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                others2MouseClicked(evt);
            }
        });
        menuBar.add(others2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 160, 50));

        userName10.setForeground(new java.awt.Color(255, 255, 255));
        userName10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-police-car-24.png"))); // NOI18N
        menuBar.add(userName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 50));

        profileImg1.setForeground(new java.awt.Color(255, 255, 255));
        profileImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-police-80.png"))); // NOI18N
        menuBar.add(profileImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 80, -1));

        logOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("Log Out");
        menuBar.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 60, -1));

        policeInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        policeInfo.setForeground(new java.awt.Color(255, 255, 255));
        policeInfo.setText("Police Information");
        policeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policeInfoMouseClicked(evt);
            }
        });
        menuBar.add(policeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 160, 50));

        userName3.setForeground(new java.awt.Color(255, 255, 255));
        userName3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-police-24.png"))); // NOI18N
        menuBar.add(userName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 50));

        others1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        others1.setForeground(new java.awt.Color(255, 255, 255));
        others1.setText("Vehicle Information");
        others1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                others1MouseClicked(evt);
            }
        });
        others1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                others1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        menuBar.add(others1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 160, 50));

        dumInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dumInfo.setForeground(new java.awt.Color(255, 255, 255));
        dumInfo.setText("Dumpyard");
        dumInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dumInfoMouseClicked(evt);
            }
        });
        menuBar.add(dumInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 160, 50));

        userName7.setForeground(new java.awt.Color(255, 255, 255));
        userName7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-modern-server-computer-stacked-on-each-other-24.png"))); // NOI18N
        menuBar.add(userName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 50));

        personalInfo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        personalInfo.setForeground(new java.awt.Color(153, 153, 153));
        personalInfo.setText("Personal Information");
        menuBar.add(personalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 150, -1));

        userName9.setForeground(new java.awt.Color(255, 255, 255));
        userName9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Book of record.png"))); // NOI18N
        menuBar.add(userName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 50));

        addNewAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addNewAdmin.setForeground(new java.awt.Color(255, 255, 255));
        addNewAdmin.setText("Add New Admin");
        menuBar.add(addNewAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 100, -1));

        caseInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        caseInfo.setForeground(new java.awt.Color(255, 255, 255));
        caseInfo.setText("Case Information");
        caseInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseInfoMouseClicked(evt);
            }
        });
        menuBar.add(caseInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 160, 50));

        userName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userName1.setForeground(new java.awt.Color(255, 255, 255));
        userName1.setText("MinhajulIslam");
        menuBar.add(userName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        dash1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dash1.setForeground(new java.awt.Color(255, 255, 255));
        dash1.setText("Dashboard");
        dash1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash1MouseExited(evt);
            }
        });
        menuBar.add(dash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 160, 50));

        getContentPane().add(menuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, 670));

        menuItem.setBackground(new java.awt.Color(255, 204, 204));
        menuItem.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(224, 221, 221));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setBackground(new java.awt.Color(153, 51, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel41.setOpaque(true);
        jPanel13.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 102, 102));
        jLabel42.setText("VEHICLE");
        jPanel13.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("250");
        jPanel13.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setBackground(new java.awt.Color(102, 204, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel44.setOpaque(true);
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 102, 102));
        jLabel45.setText("TOTAL CASE");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel46.setText("250");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 230, 100));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setBackground(new java.awt.Color(234, 87, 55));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel47.setOpaque(true);
        jPanel15.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 102));
        jLabel48.setText("PENDING");
        jPanel15.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel49.setText("250");
        jPanel15.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setBackground(new java.awt.Color(102, 204, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel50.setOpaque(true);
        jPanel16.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 102, 102));
        jLabel51.setText("TOTAL CASE");
        jPanel16.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("250");
        jPanel16.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 230, 100));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setBackground(new java.awt.Color(255, 0, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel59.setOpaque(true);
        jPanel19.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(102, 102, 102));
        jLabel60.setText("GUNS");
        jPanel19.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel61.setText("250");
        jPanel19.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setBackground(new java.awt.Color(102, 204, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel62.setOpaque(true);
        jPanel20.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(102, 102, 102));
        jLabel63.setText("TOTAL CASE");
        jPanel20.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel64.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel64.setText("250");
        jPanel20.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 230, 100));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setBackground(new java.awt.Color(0, 204, 204));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel35.setOpaque(true);
        jPanel11.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("POLICE");
        jPanel11.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("250");
        jPanel11.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setBackground(new java.awt.Color(102, 204, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel38.setOpaque(true);
        jPanel12.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("TOTAL CASE");
        jPanel12.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("250");
        jPanel12.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 230, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Version 1.0");
        dashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 234, 16));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 147, 87));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel4.setOpaque(true);
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("SOLVED");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("250");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(102, 204, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel10.setOpaque(true);
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("TOTAL CASE");
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("250");
        jPanel10.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 230, 100));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setBackground(new java.awt.Color(0, 174, 245));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel53.setOpaque(true);
        jPanel17.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(102, 102, 102));
        jLabel54.setText("TOTAL CASE");
        jPanel17.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("250");
        jPanel17.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setBackground(new java.awt.Color(102, 204, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel56.setOpaque(true);
        jPanel18.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 102, 102));
        jLabel57.setText("TOTAL CASE");
        jPanel18.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel58.setText("250");
        jPanel18.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 100));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Dashboard  >");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Home  >");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        dashboard.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1030, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Dashboard");
        dashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 21, -1, -1));

        menuItem.add(dashboard, "card2");

        getContentPane().add(menuItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 1050, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criminalInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criminalInfoMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_criminalInfoMouseClicked

    private void generalDiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalDiaryMouseClicked
        // TODO add your handling code here:

       
    }//GEN-LAST:event_generalDiaryMouseClicked

    private void others2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_others2MouseClicked

        

        // TODO add your handling code here:
    }//GEN-LAST:event_others2MouseClicked

    private void policeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeInfoMouseClicked
        // TODO add your handling code here:

        
        
       

        //        caseborad.setVisible(false);
        //        criminalborad.setVisible(false);
        //        gdboard.setVisible(false);
        //        dumpboard.setVisible(false);
        //        vehicleboard.setVisible(false);
        //        armsboard.setVisible(false);
        //        dashboard.setVisible(false);
        //        policeboard.setVisible(true);

    }//GEN-LAST:event_policeInfoMouseClicked

    private void others1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_others1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_others1MouseClicked

    private void others1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_others1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_others1CaretPositionChanged

    private void dumInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dumInfoMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_dumInfoMouseClicked

    private void caseInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caseInfoMouseClicked

       

    }//GEN-LAST:event_caseInfoMouseClicked

    private void dash1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseClicked

    private void dash1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseEntered

    private void dash1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activity;
    private javax.swing.JLabel addNewAdmin;
    private javax.swing.JLabel caseInfo;
    private javax.swing.JLabel criminalInfo;
    private javax.swing.JLabel dash1;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel dumInfo;
    private javax.swing.JLabel editProfile;
    private javax.swing.JLabel generalDiary;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logOut;
    private javax.swing.JPanel logoSite;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel menuItem;
    private javax.swing.JLabel others;
    private javax.swing.JLabel others1;
    private javax.swing.JLabel others2;
    private javax.swing.JLabel personalInfo;
    private javax.swing.JLabel policeInfo;
    private javax.swing.JLabel profileImg1;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userName1;
    private javax.swing.JLabel userName10;
    private javax.swing.JLabel userName11;
    private javax.swing.JLabel userName3;
    private javax.swing.JLabel userName5;
    private javax.swing.JLabel userName6;
    private javax.swing.JLabel userName7;
    private javax.swing.JLabel userName8;
    private javax.swing.JLabel userName9;
    // End of variables declaration//GEN-END:variables
}
