/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ps.gui;

/**
 *
 * @author Admin
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlebar = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        menubox = new javax.swing.JPanel();
        userName12 = new javax.swing.JLabel();
        userName4 = new javax.swing.JLabel();
        userName13 = new javax.swing.JLabel();
        generalDiary1 = new javax.swing.JLabel();
        policeInfo1 = new javax.swing.JLabel();
        dash1 = new javax.swing.JLabel();
        userName19 = new javax.swing.JLabel();
        activity1 = new javax.swing.JLabel();
        logOut1 = new javax.swing.JLabel();
        criminalInfo1 = new javax.swing.JLabel();
        addNewAdmin1 = new javax.swing.JLabel();
        caseInfo1 = new javax.swing.JLabel();
        userName18 = new javax.swing.JLabel();
        userName14 = new javax.swing.JLabel();
        profileImg2 = new javax.swing.JLabel();
        others4 = new javax.swing.JLabel();
        userName16 = new javax.swing.JLabel();
        userName17 = new javax.swing.JLabel();
        others3 = new javax.swing.JLabel();
        userName15 = new javax.swing.JLabel();
        editProfile1 = new javax.swing.JLabel();
        personalInfo1 = new javax.swing.JLabel();
        others5 = new javax.swing.JLabel();
        dumInfo1 = new javax.swing.JLabel();
        userName2 = new javax.swing.JLabel();
        comInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuitem = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel141 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        policeboard = new javax.swing.JPanel();
        pbhome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        createpol = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton34 = new javax.swing.JButton();
        addPol3 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlebar.setBackground(new java.awt.Color(255, 204, 204));
        titlebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Police Station Management System");
        titlebar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel142.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel142.setForeground(new java.awt.Color(153, 153, 153));
        jLabel142.setText("Version 1.0");
        jLabel142.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        titlebar.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 234, 30));

        jPanel1.add(titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 860, 50));

        menubox.setBackground(new java.awt.Color(102, 102, 102));
        menubox.setPreferredSize(new java.awt.Dimension(250, 650));
        menubox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userName12.setForeground(new java.awt.Color(255, 255, 255));
        userName12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sports-gun-24.png"))); // NOI18N
        menubox.add(userName12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 50));

        userName4.setForeground(new java.awt.Color(255, 255, 255));
        userName4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-police-24.png"))); // NOI18N
        menubox.add(userName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 50));

        userName13.setForeground(new java.awt.Color(255, 255, 255));
        userName13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Plaster.png"))); // NOI18N
        menubox.add(userName13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 50));

        generalDiary1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generalDiary1.setForeground(new java.awt.Color(255, 255, 255));
        generalDiary1.setText("General Diary");
        generalDiary1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generalDiary1MouseClicked(evt);
            }
        });
        menubox.add(generalDiary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 160, 50));

        policeInfo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        policeInfo1.setForeground(new java.awt.Color(255, 255, 255));
        policeInfo1.setText("Police Information");
        policeInfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policeInfo1MouseClicked(evt);
            }
        });
        menubox.add(policeInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, 50));

        dash1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dash1.setForeground(new java.awt.Color(255, 255, 255));
        dash1.setText("Dashboard");
        dash1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash1MouseExited(evt);
            }
        });
        menubox.add(dash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 50));

        userName19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userName19.setForeground(new java.awt.Color(255, 255, 255));
        userName19.setText("MinhajulIslam");
        menubox.add(userName19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        activity1.setForeground(new java.awt.Color(51, 255, 0));
        activity1.setText("Online");
        menubox.add(activity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        logOut1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logOut1.setForeground(new java.awt.Color(255, 255, 255));
        logOut1.setText("Log Out");
        menubox.add(logOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 60, -1));

        criminalInfo1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        criminalInfo1.setForeground(new java.awt.Color(255, 255, 255));
        criminalInfo1.setText("Criminal Information");
        criminalInfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criminalInfo1MouseClicked(evt);
            }
        });
        menubox.add(criminalInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 160, 50));

        addNewAdmin1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addNewAdmin1.setForeground(new java.awt.Color(255, 255, 255));
        addNewAdmin1.setText("Add New Admin");
        menubox.add(addNewAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 100, -1));

        caseInfo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        caseInfo1.setForeground(new java.awt.Color(255, 255, 255));
        caseInfo1.setText("Case Information");
        caseInfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseInfo1MouseClicked(evt);
            }
        });
        menubox.add(caseInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 50));

        userName18.setForeground(new java.awt.Color(255, 255, 255));
        userName18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Book of record.png"))); // NOI18N
        menubox.add(userName18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 50));

        userName14.setForeground(new java.awt.Color(255, 255, 255));
        userName14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vampire.png"))); // NOI18N
        menubox.add(userName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 50));

        profileImg2.setForeground(new java.awt.Color(255, 255, 255));
        profileImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-police-80.png"))); // NOI18N
        menubox.add(profileImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, -1));

        others4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        others4.setForeground(new java.awt.Color(255, 255, 255));
        others4.setText("Arms & Ammos");
        others4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                others4MouseClicked(evt);
            }
        });
        menubox.add(others4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 160, 50));

        userName16.setForeground(new java.awt.Color(255, 255, 255));
        userName16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-police-car-24.png"))); // NOI18N
        menubox.add(userName16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 50));

        userName17.setForeground(new java.awt.Color(255, 255, 255));
        userName17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-modern-server-computer-stacked-on-each-other-24.png"))); // NOI18N
        menubox.add(userName17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 50));

        others3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        others3.setForeground(new java.awt.Color(255, 255, 255));
        others3.setText("Others");
        menubox.add(others3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 160, 50));

        userName15.setForeground(new java.awt.Color(255, 255, 255));
        userName15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Account card.png"))); // NOI18N
        menubox.add(userName15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 50));

        editProfile1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editProfile1.setForeground(new java.awt.Color(255, 255, 255));
        editProfile1.setText("Edit Your Profile");
        menubox.add(editProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 110, -1));

        personalInfo1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        personalInfo1.setForeground(new java.awt.Color(153, 153, 153));
        personalInfo1.setText("Personal Information");
        menubox.add(personalInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 150, -1));

        others5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        others5.setForeground(new java.awt.Color(255, 255, 255));
        others5.setText("Vehicle Information");
        others5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                others5MouseClicked(evt);
            }
        });
        others5.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                others5CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        menubox.add(others5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 160, 50));

        dumInfo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dumInfo1.setForeground(new java.awt.Color(255, 255, 255));
        dumInfo1.setText("Dumpyard");
        dumInfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dumInfo1MouseClicked(evt);
            }
        });
        menubox.add(dumInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 160, 50));

        userName2.setForeground(new java.awt.Color(255, 255, 255));
        userName2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboard_1.png"))); // NOI18N
        menubox.add(userName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 50));

        comInfo.setBackground(new java.awt.Color(44, 133, 193));
        comInfo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        comInfo.setForeground(new java.awt.Color(255, 255, 255));
        comInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comInfo.setText("Admin RahatMinhaj");
        comInfo.setOpaque(true);
        menubox.add(comInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        jLabel1.setText("jLabel1");
        menubox.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, -1, -1));

        jPanel1.add(menubox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 650));

        menuitem.setBackground(new java.awt.Color(204, 255, 204));
        menuitem.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(153, 204, 255));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel141.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel141.setText("Dashboard");
        dashboard.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 21, -1, -1));

        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel135.setBackground(new java.awt.Color(255, 0, 255));
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel135.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel135.setOpaque(true);
        jPanel43.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel136.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(102, 102, 102));
        jLabel136.setText("GUNS");
        jPanel43.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel137.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel137.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel137.setText("250");
        jPanel43.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel138.setBackground(new java.awt.Color(102, 204, 255));
        jLabel138.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel138.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel138.setOpaque(true);
        jPanel44.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel139.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(102, 102, 102));
        jLabel139.setText("TOTAL CASE");
        jPanel44.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel140.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel140.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel140.setText("250");
        jPanel44.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel43.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 230, 100));

        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel110.setBackground(new java.awt.Color(153, 51, 255));
        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel110.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel110.setOpaque(true);
        jPanel34.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel111.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(102, 102, 102));
        jLabel111.setText("VEHICLE");
        jPanel34.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel112.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel112.setText("250");
        jPanel34.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel113.setBackground(new java.awt.Color(102, 204, 255));
        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel113.setOpaque(true);
        jPanel35.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel114.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(102, 102, 102));
        jLabel114.setText("TOTAL CASE");
        jPanel35.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel115.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel115.setText("250");
        jPanel35.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel34.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 230, 100));

        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel129.setBackground(new java.awt.Color(0, 174, 245));
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel129.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel129.setOpaque(true);
        jPanel41.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel130.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(102, 102, 102));
        jLabel130.setText("TOTAL CASE");
        jPanel41.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel131.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel131.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel131.setText("250");
        jPanel41.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel132.setBackground(new java.awt.Color(102, 204, 255));
        jLabel132.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel132.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel132.setOpaque(true);
        jPanel42.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel133.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel133.setForeground(new java.awt.Color(102, 102, 102));
        jLabel133.setText("TOTAL CASE");
        jPanel42.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel134.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel134.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel134.setText("250");
        jPanel42.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel41.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 100));

        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel123.setBackground(new java.awt.Color(0, 147, 87));
        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel123.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel123.setOpaque(true);
        jPanel39.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel124.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(102, 102, 102));
        jLabel124.setText("SOLVED");
        jPanel39.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel125.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel125.setText("250");
        jPanel39.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel126.setBackground(new java.awt.Color(102, 204, 255));
        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel126.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel126.setOpaque(true);
        jPanel40.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel127.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(102, 102, 102));
        jLabel127.setText("TOTAL CASE");
        jPanel40.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel128.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel128.setText("250");
        jPanel40.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel39.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 230, 100));

        jPanel36.setBackground(new java.awt.Color(204, 204, 204));
        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Dashboard  >");
        jPanel36.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 100, 30));

        jLabel116.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel116.setText("Home  >");
        jPanel36.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 30));

        dashboard.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 790, 30));

        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel117.setBackground(new java.awt.Color(234, 87, 55));
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel117.setOpaque(true);
        jPanel37.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel118.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(102, 102, 102));
        jLabel118.setText("PENDING");
        jPanel37.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel119.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel119.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel119.setText("250");
        jPanel37.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel120.setBackground(new java.awt.Color(102, 204, 255));
        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel120.setOpaque(true);
        jPanel38.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel121.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(102, 102, 102));
        jLabel121.setText("TOTAL CASE");
        jPanel38.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel122.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel122.setText("250");
        jPanel38.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        jPanel37.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 230, 100));

        dashboard.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 230, 100));

        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel145.setBackground(new java.awt.Color(102, 204, 255));
        jLabel145.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel145.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-case-66.png"))); // NOI18N
        jLabel145.setOpaque(true);
        jPanel46.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        jLabel146.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel146.setForeground(new java.awt.Color(102, 102, 102));
        jLabel146.setText("TOTAL CASE");
        jPanel46.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel147.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel147.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel147.setText("250");
        jPanel46.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        dashboard.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 230, 100));

        jLabel148.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel148.setForeground(new java.awt.Color(153, 153, 153));
        jLabel148.setText("Version 1.0");
        dashboard.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 234, 16));

        jLabel2.setText("jLabel2");
        dashboard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, 20));

        menuitem.add(dashboard, "card3");

        policeboard.setBackground(new java.awt.Color(204, 204, 255));
        policeboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pbhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Police List:");
        pbhome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pbhome.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 860, 440));

        policeboard.add(pbhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 860, 480));

        createpol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Please Input Police Details:");
        createpol.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Police ID:");
        createpol.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, 30));

        jTextField1.setText("jTextField1");
        createpol.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Police ID:");
        createpol.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 110, 30));

        jTextField2.setText("jTextField1");
        createpol.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Fist Name:");
        createpol.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, 30));

        jTextField3.setText("jTextField1");
        createpol.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Last Name");
        createpol.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 110, 30));

        jTextField4.setText("jTextField1");
        createpol.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 200, 30));

        policeboard.add(createpol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 860, 360));

        jButton34.setText("Create Role");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        policeboard.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, 40));

        addPol3.setText("Add New Police");
        addPol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPol3ActionPerformed(evt);
            }
        });
        policeboard.add(addPol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 40));

        jButton36.setText("Find Police");
        jButton36.setActionCommand("Close Case");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        policeboard.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 130, 40));

        jButton33.setText("Solved/Closed Case");
        jButton33.setActionCommand("Close Case");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        policeboard.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 130, 40));

        jButton35.setText("Closed Case");
        jButton35.setActionCommand("Close Case");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        policeboard.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 130, 40));

        jButton37.setText("Police Information Update");
        jButton37.setActionCommand("Close Case");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        policeboard.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 130, 40));

        menuitem.add(policeboard, "card4");

        jPanel1.add(menuitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 860, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalDiary1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalDiary1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_generalDiary1MouseClicked

    private void policeInfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeInfo1MouseClicked
        // TODO add your handling code here:
        
        dashboard.setVisible(false);
        policeboard.setVisible(true);
        pbhome.setVisible(true);

        //        caseborad.setVisible(false);
        //        criminalborad.setVisible(false);
        //        gdboard.setVisible(false);
        //        dumpboard.setVisible(false);
        //        vehicleboard.setVisible(false);
        //        armsboard.setVisible(false);
        //        dashboard.setVisible(false);
        //        policeboard.setVisible(true);
    }//GEN-LAST:event_policeInfo1MouseClicked

    private void dash1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseClicked
        // TODO add your handling code here:
        
        
        policeboard.setVisible(false);
        dashboard.setVisible(true);
    }//GEN-LAST:event_dash1MouseClicked

    private void dash1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseEntered

    private void dash1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseExited

    private void criminalInfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criminalInfo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_criminalInfo1MouseClicked

    private void caseInfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caseInfo1MouseClicked

    }//GEN-LAST:event_caseInfo1MouseClicked

    private void others4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_others4MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_others4MouseClicked

    private void others5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_others5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_others5MouseClicked

    private void others5CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_others5CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_others5CaretPositionChanged

    private void dumInfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dumInfo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dumInfo1MouseClicked

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        findPolice fp = new findPolice();
        fp.setVisible(true);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void addPol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPol3ActionPerformed

        pbhome.setVisible(false);
        createpol.setVisible(true);
        
    }//GEN-LAST:event_addPol3ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activity1;
    private javax.swing.JLabel addNewAdmin1;
    private javax.swing.JButton addPol3;
    private javax.swing.JLabel caseInfo1;
    private javax.swing.JLabel comInfo;
    private javax.swing.JPanel createpol;
    private javax.swing.JLabel criminalInfo1;
    private javax.swing.JLabel dash1;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel dumInfo1;
    private javax.swing.JLabel editProfile1;
    private javax.swing.JLabel generalDiary1;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel logOut1;
    private javax.swing.JPanel menubox;
    private javax.swing.JPanel menuitem;
    private javax.swing.JLabel others3;
    private javax.swing.JLabel others4;
    private javax.swing.JLabel others5;
    private javax.swing.JPanel pbhome;
    private javax.swing.JLabel personalInfo1;
    private javax.swing.JLabel policeInfo1;
    private javax.swing.JPanel policeboard;
    private javax.swing.JLabel profileImg2;
    private javax.swing.JPanel titlebar;
    private javax.swing.JLabel userName12;
    private javax.swing.JLabel userName13;
    private javax.swing.JLabel userName14;
    private javax.swing.JLabel userName15;
    private javax.swing.JLabel userName16;
    private javax.swing.JLabel userName17;
    private javax.swing.JLabel userName18;
    private javax.swing.JLabel userName19;
    private javax.swing.JLabel userName2;
    private javax.swing.JLabel userName4;
    // End of variables declaration//GEN-END:variables
}
