/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ps.gui;

import com.ps.common.IcommonDAO;
import com.ps.util.dbConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class policeLogin extends javax.swing.JFrame implements IcommonDAO{
    

    /**
     * Creates new form policeLogin
     */
    public policeLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    
    
    
    @Override
    public void loginVal() {     
        String userBox = userName.getText();
        String passBox = passInput.getText();
        
        try {
              dbConnection con = new dbConnection();
              PreparedStatement ps = con.dbConnect().prepareStatement("select * from login_details where role = 'super'");
              
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Exception from login Val Method");
        }
        
        
        
        
                
        
        if(RoleSelection.getSelectedItem().equals("Police Super")){
             try {
                 
               dbConnection con = new dbConnection();
               PreparedStatement ps = con.dbConnect().prepareStatement("select * from login_details where designation = 'super'");
               ResultSet rs = ps.executeQuery();
//               JOptionPane.showMessageDialog(rootPane, "alright");

               while(rs.next()){
                if(userBox.equalsIgnoreCase(rs.getString("user_name"))){
                    try {
                        PreparedStatement passV = con.dbConnect().prepareStatement("select password from login_details where user_name = ?");
                         passV.setString(1, userName.getText());
                        ResultSet rspassv = passV.executeQuery();
                        System.out.println("before excep");
                        System.out.println(passBox);
                        if(passBox.equalsIgnoreCase(rspassv.getString("password"))){
                        System.out.println("after excep");

                            JOptionPane.showMessageDialog(rootPane, "Login Successfull and the pass is mathched");
                            dispose();
                            DashBoard2 db = new DashBoard2();
                            db.setVisible(true);
                            
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Password Is not Matched");
                        }
       
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "Exception Caught in method after pass validation");
                        System.out.println(e);
                    }

                }else{
                    JOptionPane.showMessageDialog(rootPane, "user Name is not valid");
                }
                   
               }
                 
                
            } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "Exception Caught at the end of the method");
                 System.out.println(e);

            }


            
        }else{
            JOptionPane jo = new JOptionPane();
            jo.showMessageDialog(rootPane, "Not Selected Police ");
           
        }
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RoleSelection = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passInput = new javax.swing.JPasswordField();
        showPass = new javax.swing.JCheckBox();
        userName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 700));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rsz_police-icon-29954.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 390, 420));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 180, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Police Station Management");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 600, 80));

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(520, 700));
        jPanel3.setPreferredSize(new java.awt.Dimension(520, 700));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Select Role:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, 40));

        RoleSelection.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoleSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Police Super", "Officer Incharge", "Sub-Inspector", "Admin" }));
        RoleSelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RoleSelectionItemStateChanged(evt);
            }
        });
        RoleSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleSelectionActionPerformed(evt);
            }
        });
        jPanel3.add(RoleSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 230, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 100, 50));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 100, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/door-key-icon (2).png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 35, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/corporate-user-icon (1) (1).png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 35, 35));

        passInput.setMinimumSize(new java.awt.Dimension(64, 31));
        jPanel3.add(passInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 230, 30));

        showPass.setText("Show Password");
        showPass.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        jPanel3.add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, 40));

        userName.setMinimumSize(new java.awt.Dimension(64, 31));
        userName.setPreferredSize(new java.awt.Dimension(64, 31));
        jPanel3.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 230, -1));

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    
        
        loginVal();
        
        
//        if(RoleSelection.getSelectedItem().equals("Police Super")){
//             try {
//                 dbConnection con = new dbConnection();
//                 String sql = "select * from station_managers where role = 'super'";
//                 con.dbConnect().prepareStatement(sql);
//                 
//                 
//                
//                PreparedStatement st = con.prepareStatement(sql);
//                ResultSet rs = st.executeQuery();
//
//               while(rs.next()){
//                   String sta =  rs.getString("user_name");
//                    System.out.println(sta);
//                
//                if(user.equalsIgnoreCase(sta)){
//                    System.out.println("user name is valid");
//                }else{
//                    System.out.println("user name is not valid");
//                }
//                   
//               }
//                 
//                
//            } catch (Exception e) {
//                System.out.println(e);
//            }
//
////            this.dispose();
////        DashBoard2 db = new DashBoard2();
////        db.setVisible(true);
//            
//        }else{
//            JOptionPane jo = new JOptionPane();
//            jo.showMessageDialog(rootPane, "Not Selected Police ");
//           
//        }
//        
//        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        System.exit(EXIT_ON_CLOSE);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void RoleSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoleSelectionActionPerformed

    private void RoleSelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RoleSelectionItemStateChanged
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_RoleSelectionItemStateChanged

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:
       if (showPass.isSelected()){
           passInput.setEchoChar((char)0);
       }else{
           passInput.setEchoChar('*');
       }
    }//GEN-LAST:event_showPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(policeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(policeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(policeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(policeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new policeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RoleSelection;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField passInput;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

    

    
}
